# Generated by Django 2.2.8 on 2020-02-17 15:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=2048)),
                ('release_notes', models.TextField()),
                ('release_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_octet', models.IntegerField()),
                ('octets', models.IntegerField()),
                ('fixed_values', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ReleasePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_mask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebuc_app.BuildMask')),
                ('start_build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebuc_app.Build')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField(null=True)),
                ('builds', models.ManyToManyField(blank=True, to='rebuc_app.Build')),
                ('release_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebuc_app.ReleasePattern')),
            ],
        ),
    ]
